//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_SubEtapaIndicador
    {
        public Config_SubEtapaIndicador()
        {
            this.Config_RelacionIndicadorProyecto = new HashSet<Config_RelacionIndicadorProyecto>();
        }
    
        public int IdConfigSubEtapaIndicador { get; set; }
        public Nullable<int> IdIndicador { get; set; }
        public Nullable<int> IdSubEtapa { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual ICollection<Config_RelacionIndicadorProyecto> Config_RelacionIndicadorProyecto { get; set; }
        public virtual tbl_Indicadores tbl_Indicadores { get; set; }
        public virtual tbl_SubEtapas tbl_SubEtapas { get; set; }
    }
}
