//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_IndicadorResponsable
    {
        public Config_IndicadorResponsable()
        {
            this.Data_ValoresIndicador = new HashSet<Data_ValoresIndicador>();
            this.Rel_ProgramaAsociadoIndicador = new HashSet<Rel_ProgramaAsociadoIndicador>();
            this.tbl_Revisiones = new HashSet<tbl_Revisiones>();
        }
    
        public int IdConfigIndicadorResponsable { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdIndicador { get; set; }
        public Nullable<int> IdConfigRelacionIndicadorProyecto { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Config_RelacionIndicadorProyecto Config_RelacionIndicadorProyecto { get; set; }
        public virtual tbl_Indicadores tbl_Indicadores { get; set; }
        public virtual tbl_Responsables tbl_Responsables { get; set; }
        public virtual ICollection<Data_ValoresIndicador> Data_ValoresIndicador { get; set; }
        public virtual ICollection<Rel_ProgramaAsociadoIndicador> Rel_ProgramaAsociadoIndicador { get; set; }
        public virtual ICollection<tbl_Revisiones> tbl_Revisiones { get; set; }
    }
}
