//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_RelacionIndicadorProyecto
    {
        public Config_RelacionIndicadorProyecto()
        {
            this.Config_IndicadorResponsable = new HashSet<Config_IndicadorResponsable>();
        }
    
        public int IdConfigRelacionIndicadorProyecto { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> IdConfigSubEtapaIndicador { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCompromisoParaEmpezarAMostrarse { get; set; }
        public Nullable<int> FrecuenciaActualizacionDesdeProyecto { get; set; }
    
        public virtual ICollection<Config_IndicadorResponsable> Config_IndicadorResponsable { get; set; }
        public virtual Config_SubEtapaIndicador Config_SubEtapaIndicador { get; set; }
        public virtual tbl_Proyectos tbl_Proyectos { get; set; }
    }
}
