//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_FechasSubEtapasProyecto
    {
        public int IdConfigFechasSubEtapasProyecto { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> IdSubEtapa { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string EstatusTiempo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual tbl_Proyectos tbl_Proyectos { get; set; }
        public virtual tbl_SubEtapas tbl_SubEtapas { get; set; }
    }
}
