//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Publicaciones
    {
        public Dashboard_Publicaciones()
        {
            this.Dashboard_PublicacionAvanceGlobal = new HashSet<Dashboard_PublicacionAvanceGlobal>();
            this.Dashboard_PublicacionAvanceSubsistema = new HashSet<Dashboard_PublicacionAvanceSubsistema>();
            this.Dashboard_PublicacionElemento = new HashSet<Dashboard_PublicacionElemento>();
            this.Dashboard_PublicacionProyectoEtapa = new HashSet<Dashboard_PublicacionProyectoEtapa>();
            this.Dashboard_PublicacionProyectos = new HashSet<Dashboard_PublicacionProyectos>();
            this.Dashboard_PublicacionProyectoSubetapa = new HashSet<Dashboard_PublicacionProyectoSubetapa>();
            this.Dashboard_PublicacionTabular = new HashSet<Dashboard_PublicacionTabular>();
        }
    
        public int IdPublicacion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string TipoPublicacion { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
    
        public virtual ICollection<Dashboard_PublicacionAvanceGlobal> Dashboard_PublicacionAvanceGlobal { get; set; }
        public virtual ICollection<Dashboard_PublicacionAvanceSubsistema> Dashboard_PublicacionAvanceSubsistema { get; set; }
        public virtual ICollection<Dashboard_PublicacionElemento> Dashboard_PublicacionElemento { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectoEtapa> Dashboard_PublicacionProyectoEtapa { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectos> Dashboard_PublicacionProyectos { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectoSubetapa> Dashboard_PublicacionProyectoSubetapa { get; set; }
        public virtual ICollection<Dashboard_PublicacionTabular> Dashboard_PublicacionTabular { get; set; }
    }
}
