//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_PublicacionElemento
    {
        public int IdPublicacionElemento { get; set; }
        public string NombreElemento { get; set; }
        public Nullable<int> IdElemento { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Semaforo { get; set; }
        public Nullable<int> EstatusMejora { get; set; }
        public Nullable<int> IdSubsistema { get; set; }
        public Nullable<int> IdPublicacion { get; set; }
    
        public virtual Dashboard_Publicaciones Dashboard_Publicaciones { get; set; }
        public virtual tbl_Elementos tbl_Elementos { get; set; }
        public virtual tbl_Subsistemas tbl_Subsistemas { get; set; }
    }
}
