//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_PublicacionAvanceGlobal
    {
        public int IdPublicacionAvanceG { get; set; }
        public Nullable<int> IdPublicacion { get; set; }
        public Nullable<int> Valor { get; set; }
        public string EstatusMejora { get; set; }
    
        public virtual Dashboard_Publicaciones Dashboard_Publicaciones { get; set; }
    }
}
