//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_ValoresIndicador
    {
        public Data_ValoresIndicador()
        {
            this.Predata__ValoresIndicadoresPrograma = new HashSet<Predata__ValoresIndicadoresPrograma>();
            this.Predata_ValoresIndicadoresFormula = new HashSet<Predata_ValoresIndicadoresFormula>();
            this.tbl_ComentariosAsignadosIndicador = new HashSet<tbl_ComentariosAsignadosIndicador>();
            this.tbl_SoportesAsignadosaIndicador = new HashSet<tbl_SoportesAsignadosaIndicador>();
        }
    
        public int IdDataValoresIndicadores { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<System.DateTime> FecCreacion { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdConfigIndicadorResponsable { get; set; }
    
        public virtual Config_IndicadorResponsable Config_IndicadorResponsable { get; set; }
        public virtual ICollection<Predata__ValoresIndicadoresPrograma> Predata__ValoresIndicadoresPrograma { get; set; }
        public virtual ICollection<Predata_ValoresIndicadoresFormula> Predata_ValoresIndicadoresFormula { get; set; }
        public virtual ICollection<tbl_ComentariosAsignadosIndicador> tbl_ComentariosAsignadosIndicador { get; set; }
        public virtual ICollection<tbl_SoportesAsignadosaIndicador> tbl_SoportesAsignadosaIndicador { get; set; }
    }
}
