//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class dbSDCEntities : DbContext
    {
        public dbSDCEntities()
            : base("name=dbSDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config_Avisos> Config_Avisos { get; set; }
        public virtual DbSet<Config_FechasEtapasProyecto> Config_FechasEtapasProyecto { get; set; }
        public virtual DbSet<Config_FechasSubEtapasProyecto> Config_FechasSubEtapasProyecto { get; set; }
        public virtual DbSet<Config_IndicadorResponsable> Config_IndicadorResponsable { get; set; }
        public virtual DbSet<Config_RelacionIndicadorProyecto> Config_RelacionIndicadorProyecto { get; set; }
        public virtual DbSet<Config_SubEtapaIndicador> Config_SubEtapaIndicador { get; set; }
        public virtual DbSet<Dashboard_PublicacionAvanceGlobal> Dashboard_PublicacionAvanceGlobal { get; set; }
        public virtual DbSet<Dashboard_PublicacionAvanceSubsistema> Dashboard_PublicacionAvanceSubsistema { get; set; }
        public virtual DbSet<Dashboard_PublicacionElemento> Dashboard_PublicacionElemento { get; set; }
        public virtual DbSet<Dashboard_Publicaciones> Dashboard_Publicaciones { get; set; }
        public virtual DbSet<Dashboard_PublicacionProyectoEtapa> Dashboard_PublicacionProyectoEtapa { get; set; }
        public virtual DbSet<Dashboard_PublicacionProyectos> Dashboard_PublicacionProyectos { get; set; }
        public virtual DbSet<Dashboard_PublicacionProyectoSubetapa> Dashboard_PublicacionProyectoSubetapa { get; set; }
        public virtual DbSet<Dashboard_PublicacionTabular> Dashboard_PublicacionTabular { get; set; }
        public virtual DbSet<Data_ValoresIndicador> Data_ValoresIndicador { get; set; }
        public virtual DbSet<LogAuditoria> LogAuditoria { get; set; }
        public virtual DbSet<Predata__ValoresIndicadoresPrograma> Predata__ValoresIndicadoresPrograma { get; set; }
        public virtual DbSet<Predata_ValoresIndicadoresFormula> Predata_ValoresIndicadoresFormula { get; set; }
        public virtual DbSet<Rel_ProgramaAsociadoIndicador> Rel_ProgramaAsociadoIndicador { get; set; }
        public virtual DbSet<RunTime_PorcentajesProyecto> RunTime_PorcentajesProyecto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Areas> tbl_Areas { get; set; }
        public virtual DbSet<tbl_ComentariosAsignadosIndicador> tbl_ComentariosAsignadosIndicador { get; set; }
        public virtual DbSet<tbl_Coordinaciones> tbl_Coordinaciones { get; set; }
        public virtual DbSet<tbl_Elementos> tbl_Elementos { get; set; }
        public virtual DbSet<tbl_Etapas> tbl_Etapas { get; set; }
        public virtual DbSet<tbl_Gerencias> tbl_Gerencias { get; set; }
        public virtual DbSet<tbl_HistorialCambioFechas> tbl_HistorialCambioFechas { get; set; }
        public virtual DbSet<tbl_Historico> tbl_Historico { get; set; }
        public virtual DbSet<tbl_Indicadores> tbl_Indicadores { get; set; }
        public virtual DbSet<tbl_Organigrama> tbl_Organigrama { get; set; }
        public virtual DbSet<tbl_Proyectos> tbl_Proyectos { get; set; }
        public virtual DbSet<tbl_Puesto> tbl_Puesto { get; set; }
        public virtual DbSet<tbl_PuestoOrganigrama> tbl_PuestoOrganigrama { get; set; }
        public virtual DbSet<tbl_Responsables> tbl_Responsables { get; set; }
        public virtual DbSet<tbl_Revisiones> tbl_Revisiones { get; set; }
        public virtual DbSet<tbl_SoportesAsignadosaIndicador> tbl_SoportesAsignadosaIndicador { get; set; }
        public virtual DbSet<tbl_Subdirecciones> tbl_Subdirecciones { get; set; }
        public virtual DbSet<tbl_SubEtapas> tbl_SubEtapas { get; set; }
        public virtual DbSet<tbl_Subsistemas> tbl_Subsistemas { get; set; }
        public virtual DbSet<tbl_Superintendencias> tbl_Superintendencias { get; set; }
        public virtual DbSet<tbl_TipoElementoOrganigrama> tbl_TipoElementoOrganigrama { get; set; }
        public virtual DbSet<tbl_TipoProyectos> tbl_TipoProyectos { get; set; }
        public virtual DbSet<tbl_Ubicaciones> tbl_Ubicaciones { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_DevuelveDatosGrid_Result> SP_DevuelveDatosGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DevuelveDatosGrid_Result>("SP_DevuelveDatosGrid");
        }
    
        public virtual ObjectResult<string> SP_DevuelveSemaforoComentarios(Nullable<int> idDataValoresIndicadores)
        {
            var idDataValoresIndicadoresParameter = idDataValoresIndicadores.HasValue ?
                new ObjectParameter("IdDataValoresIndicadores", idDataValoresIndicadores) :
                new ObjectParameter("IdDataValoresIndicadores", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_DevuelveSemaforoComentarios", idDataValoresIndicadoresParameter);
        }
    
        public virtual ObjectResult<string> SP_DevuelveSemaforoConsiderandoMeta(Nullable<int> valor, Nullable<int> idConfigResponsable)
        {
            var valorParameter = valor.HasValue ?
                new ObjectParameter("Valor", valor) :
                new ObjectParameter("Valor", typeof(int));
    
            var idConfigResponsableParameter = idConfigResponsable.HasValue ?
                new ObjectParameter("IdConfigResponsable", idConfigResponsable) :
                new ObjectParameter("IdConfigResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_DevuelveSemaforoConsiderandoMeta", valorParameter, idConfigResponsableParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_GenerarHistoricoDiario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GenerarHistoricoDiario");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_InsertConfigIndicador12MPICompromisos(Nullable<int> idIndicador, Nullable<bool> checkAplica)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var checkAplicaParameter = checkAplica.HasValue ?
                new ObjectParameter("CheckAplica", checkAplica) :
                new ObjectParameter("CheckAplica", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertConfigIndicador12MPICompromisos", idIndicadorParameter, checkAplicaParameter);
        }
    
        public virtual int SP_InsertConfigResponIndSubEProyectos(Nullable<int> idConfigRelacionIndicadorProyecto, Nullable<int> idIndicador, Nullable<int> idResponsable, Nullable<bool> estatus)
        {
            var idConfigRelacionIndicadorProyectoParameter = idConfigRelacionIndicadorProyecto.HasValue ?
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", idConfigRelacionIndicadorProyecto) :
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", typeof(int));
    
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertConfigResponIndSubEProyectos", idConfigRelacionIndicadorProyectoParameter, idIndicadorParameter, idResponsableParameter, estatusParameter);
        }
    
        public virtual int SP_InsertConfigResponsables12MPI(Nullable<int> idIndicador, Nullable<int> idResponsable, Nullable<bool> estatus)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertConfigResponsables12MPI", idIndicadorParameter, idResponsableParameter, estatusParameter);
        }
    
        public virtual int SP_InsertConfigSubEtapasIndicadorCompromisos(Nullable<int> idIndicador, Nullable<int> idSubEtapa, Nullable<bool> estatus)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertConfigSubEtapasIndicadorCompromisos", idIndicadorParameter, idSubEtapaParameter, estatusParameter);
        }
    
        public virtual int SP_InsertConfiguracionProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertConfiguracionProyecto", idProyectoParameter);
        }
    
        public virtual int SP_InsertIndicadorDesdeProyecto(Nullable<int> idProyecto, Nullable<int> idSubEtapa, Nullable<int> idIndicador)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertIndicadorDesdeProyecto", idProyectoParameter, idSubEtapaParameter, idIndicadorParameter);
        }
    
        public virtual int SP_InsertIndicadoresProyecto_v2(Nullable<int> idConfigIndicadorResponsable)
        {
            var idConfigIndicadorResponsableParameter = idConfigIndicadorResponsable.HasValue ?
                new ObjectParameter("IdConfigIndicadorResponsable", idConfigIndicadorResponsable) :
                new ObjectParameter("IdConfigIndicadorResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertIndicadoresProyecto_v2", idConfigIndicadorResponsableParameter);
        }
    
        public virtual int SP_InsertProgramaAsociadoNuevoIndicador(Nullable<int> idIndicador, Nullable<int> idUsuario)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertProgramaAsociadoNuevoIndicador", idIndicadorParameter, idUsuarioParameter);
        }
    
        public virtual int SP_InsertProgramaConfigIndicadorResponsable(Nullable<int> idConfigIndicadorResponsable, Nullable<int> idIndicador)
        {
            var idConfigIndicadorResponsableParameter = idConfigIndicadorResponsable.HasValue ?
                new ObjectParameter("IdConfigIndicadorResponsable", idConfigIndicadorResponsable) :
                new ObjectParameter("IdConfigIndicadorResponsable", typeof(int));
    
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertProgramaConfigIndicadorResponsable", idConfigIndicadorResponsableParameter, idIndicadorParameter);
        }
    
        public virtual int SP_InsertPuesto(Nullable<int> idElemento, Nullable<int> idTipoElemento, string nombrePuesto, string clave)
        {
            var idElementoParameter = idElemento.HasValue ?
                new ObjectParameter("IdElemento", idElemento) :
                new ObjectParameter("IdElemento", typeof(int));
    
            var idTipoElementoParameter = idTipoElemento.HasValue ?
                new ObjectParameter("IdTipoElemento", idTipoElemento) :
                new ObjectParameter("IdTipoElemento", typeof(int));
    
            var nombrePuestoParameter = nombrePuesto != null ?
                new ObjectParameter("NombrePuesto", nombrePuesto) :
                new ObjectParameter("NombrePuesto", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertPuesto", idElementoParameter, idTipoElementoParameter, nombrePuestoParameter, claveParameter);
        }
    
        public virtual int SP_InsertRevisiones12MPI(Nullable<int> idConfigIndicadorResponsable)
        {
            var idConfigIndicadorResponsableParameter = idConfigIndicadorResponsable.HasValue ?
                new ObjectParameter("IdConfigIndicadorResponsable", idConfigIndicadorResponsable) :
                new ObjectParameter("IdConfigIndicadorResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertRevisiones12MPI", idConfigIndicadorResponsableParameter);
        }
    
        public virtual int SP_InsertRevisionesIndicadoresSubEtapas(Nullable<int> idConfigIndicadorResponsable, Nullable<int> idSubEtapa, Nullable<int> idProyecto)
        {
            var idConfigIndicadorResponsableParameter = idConfigIndicadorResponsable.HasValue ?
                new ObjectParameter("IdConfigIndicadorResponsable", idConfigIndicadorResponsable) :
                new ObjectParameter("IdConfigIndicadorResponsable", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertRevisionesIndicadoresSubEtapas", idConfigIndicadorResponsableParameter, idSubEtapaParameter, idProyectoParameter);
        }
    
        public virtual int SP_InsertSemaforosdeProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertSemaforosdeProyecto", idProyectoParameter);
        }
    
        public virtual int SP_InsertValoresdeMesesxSubsistemasxPublicacion(Nullable<int> idPublicacion, Nullable<int> idUbicacion)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            var idUbicacionParameter = idUbicacion.HasValue ?
                new ObjectParameter("IdUbicacion", idUbicacion) :
                new ObjectParameter("IdUbicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertValoresdeMesesxSubsistemasxPublicacion", idPublicacionParameter, idUbicacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_InsertValoresIndicadores(Nullable<int> idDataValoresIndicadores, Nullable<double> valor, Nullable<int> idConfigIndicadorResponsable)
        {
            var idDataValoresIndicadoresParameter = idDataValoresIndicadores.HasValue ?
                new ObjectParameter("IdDataValoresIndicadores", idDataValoresIndicadores) :
                new ObjectParameter("IdDataValoresIndicadores", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("Valor", valor) :
                new ObjectParameter("Valor", typeof(double));
    
            var idConfigIndicadorResponsableParameter = idConfigIndicadorResponsable.HasValue ?
                new ObjectParameter("IdConfigIndicadorResponsable", idConfigIndicadorResponsable) :
                new ObjectParameter("IdConfigIndicadorResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_InsertValoresIndicadores", idDataValoresIndicadoresParameter, valorParameter, idConfigIndicadorResponsableParameter);
        }
    
        public virtual ObjectResult<string> SP_ProcesodePublicacion(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ProcesodePublicacion", tipoParameter);
        }
    
        public virtual int SP_RecalculoRevisionesEnProyectos(Nullable<int> idProyectoPar, Nullable<int> idSubEtapaPar)
        {
            var idProyectoParParameter = idProyectoPar.HasValue ?
                new ObjectParameter("IdProyectoPar", idProyectoPar) :
                new ObjectParameter("IdProyectoPar", typeof(int));
    
            var idSubEtapaParParameter = idSubEtapaPar.HasValue ?
                new ObjectParameter("IdSubEtapaPar", idSubEtapaPar) :
                new ObjectParameter("IdSubEtapaPar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RecalculoRevisionesEnProyectos", idProyectoParParameter, idSubEtapaParParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_Select_ProgramaAsociadoxIndicador_Result> SP_Select_ProgramaAsociadoxIndicador(Nullable<int> idIndicador)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_ProgramaAsociadoxIndicador_Result>("SP_Select_ProgramaAsociadoxIndicador", idIndicadorParameter);
        }
    
        public virtual ObjectResult<SP_Select_Publicacion_Result> SP_Select_Publicacion(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_Publicacion_Result>("SP_Select_Publicacion", tipoParameter);
        }
    
        public virtual ObjectResult<SP_Select_PublicacionAvanceGlobal_Result> SP_Select_PublicacionAvanceGlobal(Nullable<int> idPublicacion)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_PublicacionAvanceGlobal_Result>("SP_Select_PublicacionAvanceGlobal", idPublicacionParameter);
        }
    
        public virtual ObjectResult<SP_Select_PublicacionElementoxSubsistema_Result> SP_Select_PublicacionElementoxSubsistema(Nullable<int> idPublicacion, Nullable<int> idSubsistema)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            var idSubsistemaParameter = idSubsistema.HasValue ?
                new ObjectParameter("IdSubsistema", idSubsistema) :
                new ObjectParameter("IdSubsistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_PublicacionElementoxSubsistema_Result>("SP_Select_PublicacionElementoxSubsistema", idPublicacionParameter, idSubsistemaParameter);
        }
    
        public virtual ObjectResult<SP_Select_PublicacionSubsistemasxMesTabular_Result> SP_Select_PublicacionSubsistemasxMesTabular(Nullable<int> idPublicacion)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_PublicacionSubsistemasxMesTabular_Result>("SP_Select_PublicacionSubsistemasxMesTabular", idPublicacionParameter);
        }
    
        public virtual ObjectResult<SP_Select_PublicacionValoresSemaforosXSubsistemas_Result> SP_Select_PublicacionValoresSemaforosXSubsistemas(Nullable<int> idPublicacion)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_PublicacionValoresSemaforosXSubsistemas_Result>("SP_Select_PublicacionValoresSemaforosXSubsistemas", idPublicacionParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_Areas_Result> SP_SelectAll_Areas(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("idResponsable", idResponsable) :
                new ObjectParameter("idResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Areas_Result>("SP_SelectAll_Areas", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_BusquedaPuestoBeforeInsert_Result> SP_SelectAll_BusquedaPuestoBeforeInsert(Nullable<int> idElemento, Nullable<int> idTipoElemento, string nombrePuesto)
        {
            var idElementoParameter = idElemento.HasValue ?
                new ObjectParameter("IdElemento", idElemento) :
                new ObjectParameter("IdElemento", typeof(int));
    
            var idTipoElementoParameter = idTipoElemento.HasValue ?
                new ObjectParameter("IdTipoElemento", idTipoElemento) :
                new ObjectParameter("IdTipoElemento", typeof(int));
    
            var nombrePuestoParameter = nombrePuesto != null ?
                new ObjectParameter("NombrePuesto", nombrePuesto) :
                new ObjectParameter("NombrePuesto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_BusquedaPuestoBeforeInsert_Result>("SP_SelectAll_BusquedaPuestoBeforeInsert", idElementoParameter, idTipoElementoParameter, nombrePuestoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_ComentariosdeIndicadores_Result> SP_SelectAll_ComentariosdeIndicadores(Nullable<int> idIndicador, Nullable<int> idSubEtapa, Nullable<int> idProyecto)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_ComentariosdeIndicadores_Result>("SP_SelectAll_ComentariosdeIndicadores", idIndicadorParameter, idSubEtapaParameter, idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_ConfiguracionIndicadoresSubEtapasxProyecto_Result> SP_SelectAll_ConfiguracionIndicadoresSubEtapasxProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_ConfiguracionIndicadoresSubEtapasxProyecto_Result>("SP_SelectAll_ConfiguracionIndicadoresSubEtapasxProyecto", idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_CoordinacionesParaProyecto_Result> SP_SelectAll_CoordinacionesParaProyecto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_CoordinacionesParaProyecto_Result>("SP_SelectAll_CoordinacionesParaProyecto");
        }
    
        public virtual ObjectResult<SP_SelectAll_Elementos_Result> SP_SelectAll_Elementos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Elementos_Result>("SP_SelectAll_Elementos");
        }
    
        public virtual ObjectResult<SP_SelectAll_ElementosPorSubsistema_Result> SP_SelectAll_ElementosPorSubsistema(Nullable<int> idSubsistema)
        {
            var idSubsistemaParameter = idSubsistema.HasValue ?
                new ObjectParameter("IdSubsistema", idSubsistema) :
                new ObjectParameter("IdSubsistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_ElementosPorSubsistema_Result>("SP_SelectAll_ElementosPorSubsistema", idSubsistemaParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_FechasSubEtapasxProyecto_Result> SP_SelectAll_FechasSubEtapasxProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_FechasSubEtapasxProyecto_Result>("SP_SelectAll_FechasSubEtapasxProyecto", idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_IndicadoresGlobalesEnProceso_Result> SP_SelectAll_IndicadoresGlobalesEnProceso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_IndicadoresGlobalesEnProceso_Result>("SP_SelectAll_IndicadoresGlobalesEnProceso");
        }
    
        public virtual ObjectResult<SP_SelectAll_IndicadoresLlenosFaltantesGlobalesMonitoreo_Result> SP_SelectAll_IndicadoresLlenosFaltantesGlobalesMonitoreo(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_IndicadoresLlenosFaltantesGlobalesMonitoreo_Result>("SP_SelectAll_IndicadoresLlenosFaltantesGlobalesMonitoreo", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_IndicadoresPorElemento_Result> SP_SelectAll_IndicadoresPorElemento(Nullable<int> idElemento)
        {
            var idElementoParameter = idElemento.HasValue ?
                new ObjectParameter("IdElemento", idElemento) :
                new ObjectParameter("IdElemento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_IndicadoresPorElemento_Result>("SP_SelectAll_IndicadoresPorElemento", idElementoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_IndicadoresPorElementoFaltantesEnSubEtapaProyecto_Result> SP_SelectAll_IndicadoresPorElementoFaltantesEnSubEtapaProyecto(Nullable<int> idElemento, Nullable<int> idSubEtapa, Nullable<int> idProyecto)
        {
            var idElementoParameter = idElemento.HasValue ?
                new ObjectParameter("IdElemento", idElemento) :
                new ObjectParameter("IdElemento", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_IndicadoresPorElementoFaltantesEnSubEtapaProyecto_Result>("SP_SelectAll_IndicadoresPorElementoFaltantesEnSubEtapaProyecto", idElementoParameter, idSubEtapaParameter, idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_MonitoreoIndicadoresResponsables12MPI_Result> SP_SelectAll_MonitoreoIndicadoresResponsables12MPI(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_MonitoreoIndicadoresResponsables12MPI_Result>("SP_SelectAll_MonitoreoIndicadoresResponsables12MPI", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_MonitoreoIndicadoresResponsablesSubsistemas_Result> SP_SelectAll_MonitoreoIndicadoresResponsablesSubsistemas(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_MonitoreoIndicadoresResponsablesSubsistemas_Result>("SP_SelectAll_MonitoreoIndicadoresResponsablesSubsistemas", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_PublicacionesProyectosByTipo_Result> SP_SelectAll_PublicacionesProyectosByTipo(Nullable<int> idPublicacion, Nullable<int> idTipoProyecto)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            var idTipoProyectoParameter = idTipoProyecto.HasValue ?
                new ObjectParameter("IdTipoProyecto", idTipoProyecto) :
                new ObjectParameter("IdTipoProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_PublicacionesProyectosByTipo_Result>("SP_SelectAll_PublicacionesProyectosByTipo", idPublicacionParameter, idTipoProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_PublicacionProyectoEtapas_Result> SP_SelectAll_PublicacionProyectoEtapas(Nullable<int> idPublicacionProyecto)
        {
            var idPublicacionProyectoParameter = idPublicacionProyecto.HasValue ?
                new ObjectParameter("IdPublicacionProyecto", idPublicacionProyecto) :
                new ObjectParameter("IdPublicacionProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_PublicacionProyectoEtapas_Result>("SP_SelectAll_PublicacionProyectoEtapas", idPublicacionProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_PublicacionProyectoSubEtapas_Result> SP_SelectAll_PublicacionProyectoSubEtapas(Nullable<int> idPublicacionProyectoEtapa)
        {
            var idPublicacionProyectoEtapaParameter = idPublicacionProyectoEtapa.HasValue ?
                new ObjectParameter("IdPublicacionProyectoEtapa", idPublicacionProyectoEtapa) :
                new ObjectParameter("IdPublicacionProyectoEtapa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_PublicacionProyectoSubEtapas_Result>("SP_SelectAll_PublicacionProyectoSubEtapas", idPublicacionProyectoEtapaParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_Puestos_Result> SP_SelectAll_Puestos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Puestos_Result>("SP_SelectAll_Puestos");
        }
    
        public virtual ObjectResult<SP_SelectAll_Responsables_Result> SP_SelectAll_Responsables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Responsables_Result>("SP_SelectAll_Responsables");
        }
    
        public virtual ObjectResult<SP_SelectAll_SoportesdeIndicadores_Result> SP_SelectAll_SoportesdeIndicadores(Nullable<int> idIndicador, Nullable<int> idSubEtapa, Nullable<int> idProyecto)
        {
            var idIndicadorParameter = idIndicador.HasValue ?
                new ObjectParameter("IdIndicador", idIndicador) :
                new ObjectParameter("IdIndicador", typeof(int));
    
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_SoportesdeIndicadores_Result>("SP_SelectAll_SoportesdeIndicadores", idIndicadorParameter, idSubEtapaParameter, idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_Subsistemas_Result> SP_SelectAll_Subsistemas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Subsistemas_Result>("SP_SelectAll_Subsistemas");
        }
    
        public virtual ObjectResult<SP_SelectAll_SuperintendenciasParaProyecto_Result> SP_SelectAll_SuperintendenciasParaProyecto(Nullable<int> idCoordinacion)
        {
            var idCoordinacionParameter = idCoordinacion.HasValue ?
                new ObjectParameter("IdCoordinacion", idCoordinacion) :
                new ObjectParameter("IdCoordinacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_SuperintendenciasParaProyecto_Result>("SP_SelectAll_SuperintendenciasParaProyecto", idCoordinacionParameter);
        }
    
        public virtual ObjectResult<SP_SelectAll_TipoProyectos_Result> SP_SelectAll_TipoProyectos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_TipoProyectos_Result>("SP_SelectAll_TipoProyectos");
        }
    
        public virtual ObjectResult<SP_SelectAll_Ubicaciones_Result> SP_SelectAll_Ubicaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_Ubicaciones_Result>("SP_SelectAll_Ubicaciones");
        }
    
        public virtual ObjectResult<SP_SelectAll_ValoresSemaforoSubsistemasEnProceso_Result> SP_SelectAll_ValoresSemaforoSubsistemasEnProceso(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAll_ValoresSemaforoSubsistemasEnProceso_Result>("SP_SelectAll_ValoresSemaforoSubsistemasEnProceso", idResponsableParameter);
        }
    
        public virtual int SP_SelectAllCount_IndicadoresLlenosFaltantes12MPI(Nullable<int> tipo, Nullable<int> idResponsable)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectAllCount_IndicadoresLlenosFaltantes12MPI", tipoParameter, idResponsableParameter);
        }
    
        public virtual int SP_SelectAllCount_IndicadoresLlenosFaltantesSubsistemas(Nullable<int> idSubsistema, Nullable<int> tipo, Nullable<int> idResponsable)
        {
            var idSubsistemaParameter = idSubsistema.HasValue ?
                new ObjectParameter("IdSubsistema", idSubsistema) :
                new ObjectParameter("IdSubsistema", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectAllCount_IndicadoresLlenosFaltantesSubsistemas", idSubsistemaParameter, tipoParameter, idResponsableParameter);
        }
    
        public virtual int SP_SelectAllCount_IndicadoresLlenosFaltantesXProyecto(Nullable<int> tipo, Nullable<int> idProyecto, Nullable<int> idEtapa, Nullable<int> idSubetapa, string tipoBusqueda)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            var idEtapaParameter = idEtapa.HasValue ?
                new ObjectParameter("IdEtapa", idEtapa) :
                new ObjectParameter("IdEtapa", typeof(int));
    
            var idSubetapaParameter = idSubetapa.HasValue ?
                new ObjectParameter("IdSubetapa", idSubetapa) :
                new ObjectParameter("IdSubetapa", typeof(int));
    
            var tipoBusquedaParameter = tipoBusqueda != null ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectAllCount_IndicadoresLlenosFaltantesXProyecto", tipoParameter, idProyectoParameter, idEtapaParameter, idSubetapaParameter, tipoBusquedaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsable12MPI(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsable12MPI", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsableSubsistema_Result> SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsableSubsistema(Nullable<int> idResponsable, Nullable<int> idSubsistema)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var idSubsistemaParameter = idSubsistema.HasValue ?
                new ObjectParameter("IdSubsistema", idSubsistema) :
                new ObjectParameter("IdSubsistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsableSubsistema_Result>("SP_SelectAllCount_MonitoreoIndicadoresFaltantesxResponsableSubsistema", idResponsableParameter, idSubsistemaParameter);
        }
    
        public virtual ObjectResult<SP_SelectAllProyectosByEstatus_Result> SP_SelectAllProyectosByEstatus(string estatus)
        {
            var estatusParameter = estatus != null ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllProyectosByEstatus_Result>("SP_SelectAllProyectosByEstatus", estatusParameter);
        }
    
        public virtual ObjectResult<SP_SelectAllProyectosByEstatusAndRol_Result> SP_SelectAllProyectosByEstatusAndRol(string estatus, Nullable<int> idResponsable)
        {
            var estatusParameter = estatus != null ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(string));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllProyectosByEstatusAndRol_Result>("SP_SelectAllProyectosByEstatusAndRol", estatusParameter, idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectAllPublicacionProyectos_Result> SP_SelectAllPublicacionProyectos(Nullable<int> idPublicacion)
        {
            var idPublicacionParameter = idPublicacion.HasValue ?
                new ObjectParameter("IdPublicacion", idPublicacion) :
                new ObjectParameter("IdPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllPublicacionProyectos_Result>("SP_SelectAllPublicacionProyectos", idPublicacionParameter);
        }
    
        public virtual ObjectResult<SP_SelectAllResponsablesIndicadorXProyecto_Result> SP_SelectAllResponsablesIndicadorXProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllResponsablesIndicadorXProyecto_Result>("SP_SelectAllResponsablesIndicadorXProyecto", idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectOne_PublicacionProyectoEtapaSeleccionada_Result> SP_SelectOne_PublicacionProyectoEtapaSeleccionada(Nullable<int> idPublicacionProyectoEtapa)
        {
            var idPublicacionProyectoEtapaParameter = idPublicacionProyectoEtapa.HasValue ?
                new ObjectParameter("IdPublicacionProyectoEtapa", idPublicacionProyectoEtapa) :
                new ObjectParameter("IdPublicacionProyectoEtapa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectOne_PublicacionProyectoEtapaSeleccionada_Result>("SP_SelectOne_PublicacionProyectoEtapaSeleccionada", idPublicacionProyectoEtapaParameter);
        }
    
        public virtual ObjectResult<SP_SelectOne_PublicacionProyectoSeleccionado_Result> SP_SelectOne_PublicacionProyectoSeleccionado(Nullable<int> idPublicacionProyecto)
        {
            var idPublicacionProyectoParameter = idPublicacionProyecto.HasValue ?
                new ObjectParameter("IdPublicacionProyecto", idPublicacionProyecto) :
                new ObjectParameter("IdPublicacionProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectOne_PublicacionProyectoSeleccionado_Result>("SP_SelectOne_PublicacionProyectoSeleccionado", idPublicacionProyectoParameter);
        }
    
        public virtual ObjectResult<SP_SelectOne_Responsable_Result> SP_SelectOne_Responsable(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("idResponsable", idResponsable) :
                new ObjectParameter("idResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectOne_Responsable_Result>("SP_SelectOne_Responsable", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_SelectOne_Ubicacion_Result> SP_SelectOne_Ubicacion(Nullable<int> idUbicacion)
        {
            var idUbicacionParameter = idUbicacion.HasValue ?
                new ObjectParameter("IdUbicacion", idUbicacion) :
                new ObjectParameter("IdUbicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectOne_Ubicacion_Result>("SP_SelectOne_Ubicacion", idUbicacionParameter);
        }
    
        public virtual int SP_SelectPromedioRT12MPI(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectPromedioRT12MPI", idResponsableParameter);
        }
    
        public virtual int SP_SelectPromedioRT12MPIByUbicacion(Nullable<int> idUbicacion)
        {
            var idUbicacionParameter = idUbicacion.HasValue ?
                new ObjectParameter("IdUbicacion", idUbicacion) :
                new ObjectParameter("IdUbicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectPromedioRT12MPIByUbicacion", idUbicacionParameter);
        }
    
        public virtual int SP_SelectPromedioRTSubsistemas(Nullable<int> idSubsistema, Nullable<int> idResponsable)
        {
            var idSubsistemaParameter = idSubsistema.HasValue ?
                new ObjectParameter("IdSubsistema", idSubsistema) :
                new ObjectParameter("IdSubsistema", typeof(int));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SelectPromedioRTSubsistemas", idSubsistemaParameter, idResponsableParameter);
        }
    
        public virtual ObjectResult<string> SP_SelectTrace_Proyecto(Nullable<int> idElemento, Nullable<int> tipoElemento, ObjectParameter trace)
        {
            var idElementoParameter = idElemento.HasValue ?
                new ObjectParameter("IdElemento", idElemento) :
                new ObjectParameter("IdElemento", typeof(int));
    
            var tipoElementoParameter = tipoElemento.HasValue ?
                new ObjectParameter("TipoElemento", tipoElemento) :
                new ObjectParameter("TipoElemento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SelectTrace_Proyecto", idElementoParameter, tipoElementoParameter, trace);
        }
    
        public virtual ObjectResult<SP_SelectTrace_Puesto_Result> SP_SelectTrace_Puesto(Nullable<int> idPuesto)
        {
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectTrace_Puesto_Result>("SP_SelectTrace_Puesto", idPuestoParameter);
        }
    
        public virtual int SP_UpdateEstatusEtapaProyectos(Nullable<int> idEtapa, Nullable<int> idProyecto, Nullable<bool> estatus)
        {
            var idEtapaParameter = idEtapa.HasValue ?
                new ObjectParameter("IdEtapa", idEtapa) :
                new ObjectParameter("IdEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateEstatusEtapaProyectos", idEtapaParameter, idProyectoParameter, estatusParameter);
        }
    
        public virtual int SP_UpdateEstatusSubetapaProyectos(Nullable<int> idSubEtapa, Nullable<int> idProyecto, Nullable<bool> estatus)
        {
            var idSubEtapaParameter = idSubEtapa.HasValue ?
                new ObjectParameter("IdSubEtapa", idSubEtapa) :
                new ObjectParameter("IdSubEtapa", typeof(int));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateEstatusSubetapaProyectos", idSubEtapaParameter, idProyectoParameter, estatusParameter);
        }
    
        public virtual int SP_UpdateEstatusTiempoSubEtapaProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateEstatusTiempoSubEtapaProyecto", idProyectoParameter);
        }
    
        public virtual int SP_UpdateFechaCompromisoInCRIP(Nullable<int> idConfigRelacionIndicadorProyecto, Nullable<System.DateTime> fechaCompromisoParaEmpezarAMostrarse)
        {
            var idConfigRelacionIndicadorProyectoParameter = idConfigRelacionIndicadorProyecto.HasValue ?
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", idConfigRelacionIndicadorProyecto) :
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", typeof(int));
    
            var fechaCompromisoParaEmpezarAMostrarseParameter = fechaCompromisoParaEmpezarAMostrarse.HasValue ?
                new ObjectParameter("FechaCompromisoParaEmpezarAMostrarse", fechaCompromisoParaEmpezarAMostrarse) :
                new ObjectParameter("FechaCompromisoParaEmpezarAMostrarse", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateFechaCompromisoInCRIP", idConfigRelacionIndicadorProyectoParameter, fechaCompromisoParaEmpezarAMostrarseParameter);
        }
    
        public virtual int SP_UpdateFrecuenciaActualizacionInCRIP(Nullable<int> idConfigRelacionIndicadorProyecto, Nullable<int> frecuenciaActualizacionDesdeProyecto)
        {
            var idConfigRelacionIndicadorProyectoParameter = idConfigRelacionIndicadorProyecto.HasValue ?
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", idConfigRelacionIndicadorProyecto) :
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", typeof(int));
    
            var frecuenciaActualizacionDesdeProyectoParameter = frecuenciaActualizacionDesdeProyecto.HasValue ?
                new ObjectParameter("FrecuenciaActualizacionDesdeProyecto", frecuenciaActualizacionDesdeProyecto) :
                new ObjectParameter("FrecuenciaActualizacionDesdeProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateFrecuenciaActualizacionInCRIP", idConfigRelacionIndicadorProyectoParameter, frecuenciaActualizacionDesdeProyectoParameter);
        }
    
        public virtual int SP_UpdateRelacionIndicadorSubEtapaProyecto(Nullable<int> idConfigRelacionIndicadorProyecto, Nullable<bool> estatus)
        {
            var idConfigRelacionIndicadorProyectoParameter = idConfigRelacionIndicadorProyecto.HasValue ?
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", idConfigRelacionIndicadorProyecto) :
                new ObjectParameter("IdConfigRelacionIndicadorProyecto", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateRelacionIndicadorSubEtapaProyecto", idConfigRelacionIndicadorProyectoParameter, estatusParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadores12MPIAgrupados_Result> SP_VistaCargaIndicadores12MPIAgrupados(Nullable<int> idResponsable, Nullable<int> idUbicacionPar)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var idUbicacionParParameter = idUbicacionPar.HasValue ?
                new ObjectParameter("IdUbicacionPar", idUbicacionPar) :
                new ObjectParameter("IdUbicacionPar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadores12MPIAgrupados_Result>("SP_VistaCargaIndicadores12MPIAgrupados", idResponsableParameter, idUbicacionParParameter);
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadores12MPIxReponsable_Result> SP_VistaCargaIndicadores12MPIxReponsable(Nullable<int> idReponsable)
        {
            var idReponsableParameter = idReponsable.HasValue ?
                new ObjectParameter("IdReponsable", idReponsable) :
                new ObjectParameter("IdReponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadores12MPIxReponsable_Result>("SP_VistaCargaIndicadores12MPIxReponsable", idReponsableParameter);
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadores12MPIxReponsableSubadministrador_Result> SP_VistaCargaIndicadores12MPIxReponsableSubadministrador(Nullable<int> idReponsable, Nullable<int> idUbicacionPar)
        {
            var idReponsableParameter = idReponsable.HasValue ?
                new ObjectParameter("IdReponsable", idReponsable) :
                new ObjectParameter("IdReponsable", typeof(int));
    
            var idUbicacionParParameter = idUbicacionPar.HasValue ?
                new ObjectParameter("IdUbicacionPar", idUbicacionPar) :
                new ObjectParameter("IdUbicacionPar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadores12MPIxReponsableSubadministrador_Result>("SP_VistaCargaIndicadores12MPIxReponsableSubadministrador", idReponsableParameter, idUbicacionParParameter);
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadoresAgrupadosProyectos_Result> SP_VistaCargaIndicadoresAgrupadosProyectos(Nullable<int> idResponsable, string estatusTiempo, Nullable<int> idUbicacion)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var estatusTiempoParameter = estatusTiempo != null ?
                new ObjectParameter("EstatusTiempo", estatusTiempo) :
                new ObjectParameter("EstatusTiempo", typeof(string));
    
            var idUbicacionParameter = idUbicacion.HasValue ?
                new ObjectParameter("IdUbicacion", idUbicacion) :
                new ObjectParameter("IdUbicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadoresAgrupadosProyectos_Result>("SP_VistaCargaIndicadoresAgrupadosProyectos", idResponsableParameter, estatusTiempoParameter, idUbicacionParameter);
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadoresProyectos_Result> SP_VistaCargaIndicadoresProyectos(Nullable<int> idReponsable)
        {
            var idReponsableParameter = idReponsable.HasValue ?
                new ObjectParameter("IdReponsable", idReponsable) :
                new ObjectParameter("IdReponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadoresProyectos_Result>("SP_VistaCargaIndicadoresProyectos", idReponsableParameter);
        }
    
        public virtual ObjectResult<SP_VistaCargaIndicadoresProyectosByProyecto_Result> SP_VistaCargaIndicadoresProyectosByProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("IdProyecto", idProyecto) :
                new ObjectParameter("IdProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaCargaIndicadoresProyectosByProyecto_Result>("SP_VistaCargaIndicadoresProyectosByProyecto", idProyectoParameter);
        }
    
        public virtual ObjectResult<SP_VistaIndicadores12MPIActivadosPeroAsignados_Result> SP_VistaIndicadores12MPIActivadosPeroAsignados(Nullable<int> idResponsable)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaIndicadores12MPIActivadosPeroAsignados_Result>("SP_VistaIndicadores12MPIActivadosPeroAsignados", idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_VistaIndicadoresActivadosPeroNoAsignadosEnProyectos_Result> SP_VistaIndicadoresActivadosPeroNoAsignadosEnProyectos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaIndicadoresActivadosPeroNoAsignadosEnProyectos_Result>("SP_VistaIndicadoresActivadosPeroNoAsignadosEnProyectos");
        }
    
        public virtual ObjectResult<SP_VistaparaPivotGridProyectos_Result> SP_VistaparaPivotGridProyectos(Nullable<int> idResponsable, string estatusTiempo)
        {
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            var estatusTiempoParameter = estatusTiempo != null ?
                new ObjectParameter("EstatusTiempo", estatusTiempo) :
                new ObjectParameter("EstatusTiempo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VistaparaPivotGridProyectos_Result>("SP_VistaparaPivotGridProyectos", idResponsableParameter, estatusTiempoParameter);
        }
    }
}
