//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAuditoria
    {
        public Nullable<int> idRef { get; set; }
        public int id { get; set; }
        public string Movimiento { get; set; }
        public string Elemento { get; set; }
        public string Log { get; set; }
        public string fecha { get; set; }
        public string usuario { get; set; }
        public string personal { get; set; }
        public string rol { get; set; }
    }
}
