//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predata__ValoresIndicadoresPrograma
    {
        public int IdPreVIP { get; set; }
        public Nullable<int> IdDataValoresIndicadores { get; set; }
        public Nullable<int> EneroProg { get; set; }
        public Nullable<int> FebreroProg { get; set; }
        public Nullable<int> MarzoProg { get; set; }
        public Nullable<int> AbrilProg { get; set; }
        public Nullable<int> MayoProg { get; set; }
        public Nullable<int> JunioProg { get; set; }
        public Nullable<int> JulioProg { get; set; }
        public Nullable<int> AgostoProg { get; set; }
        public Nullable<int> SeptiembreProg { get; set; }
        public Nullable<int> OctubreProg { get; set; }
        public Nullable<int> NoviembreProg { get; set; }
        public Nullable<int> DiciembreProg { get; set; }
        public Nullable<int> ProyeccionAnualProg { get; set; }
        public Nullable<int> AnioSiguienteProg { get; set; }
        public Nullable<int> AnioAnteriorReal { get; set; }
        public Nullable<int> EneroReal { get; set; }
        public Nullable<int> FebreroReal { get; set; }
        public Nullable<int> MarzoReal { get; set; }
        public Nullable<int> AbrilReal { get; set; }
        public Nullable<int> MayoReal { get; set; }
        public Nullable<int> JunioReal { get; set; }
        public Nullable<int> JulioReal { get; set; }
        public Nullable<int> AgostoReal { get; set; }
        public Nullable<int> SeptiembreReal { get; set; }
        public Nullable<int> OctubreReal { get; set; }
        public Nullable<int> NoviembreReal { get; set; }
        public Nullable<int> DiciembreReal { get; set; }
        public Nullable<int> ProyeccionAnualReal { get; set; }
        public Nullable<int> AnioSiguienteReal { get; set; }
        public Nullable<System.DateTime> FecCreacion { get; set; }
        public Nullable<double> Resultado { get; set; }
        public Nullable<int> AnioAnteriorProg { get; set; }
    
        public virtual Data_ValoresIndicador Data_ValoresIndicador { get; set; }
    }
}
