//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Proyectos
    {
        public tbl_Proyectos()
        {
            this.Config_FechasEtapasProyecto = new HashSet<Config_FechasEtapasProyecto>();
            this.Config_FechasSubEtapasProyecto = new HashSet<Config_FechasSubEtapasProyecto>();
            this.Config_RelacionIndicadorProyecto = new HashSet<Config_RelacionIndicadorProyecto>();
            this.Dashboard_PublicacionProyectos = new HashSet<Dashboard_PublicacionProyectos>();
            this.RunTime_PorcentajesProyecto = new HashSet<RunTime_PorcentajesProyecto>();
        }
    
        public int IdProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public string EstatusTiempo { get; set; }
        public string Semaforo { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> IdElementoOrganigrama { get; set; }
        public Nullable<int> IdTipoElementoOrganigrama { get; set; }
        public Nullable<int> IdTipoProyecto { get; set; }
    
        public virtual ICollection<Config_FechasEtapasProyecto> Config_FechasEtapasProyecto { get; set; }
        public virtual ICollection<Config_FechasSubEtapasProyecto> Config_FechasSubEtapasProyecto { get; set; }
        public virtual ICollection<Config_RelacionIndicadorProyecto> Config_RelacionIndicadorProyecto { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectos> Dashboard_PublicacionProyectos { get; set; }
        public virtual ICollection<RunTime_PorcentajesProyecto> RunTime_PorcentajesProyecto { get; set; }
        public virtual tbl_Areas tbl_Areas { get; set; }
        public virtual tbl_Responsables tbl_Responsables { get; set; }
        public virtual tbl_Responsables tbl_Responsables1 { get; set; }
        public virtual tbl_Responsables tbl_Responsables2 { get; set; }
        public virtual tbl_Ubicaciones tbl_Ubicaciones { get; set; }
    }
}
