//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gerencias
    {
        public tbl_Gerencias()
        {
            this.tbl_Coordinaciones = new HashSet<tbl_Coordinaciones>();
        }
    
        public int IdGerencia { get; set; }
        public string NombreGerencia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<int> IdSubdireccion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string ClaveGerencias { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<tbl_Coordinaciones> tbl_Coordinaciones { get; set; }
        public virtual tbl_Subdirecciones tbl_Subdirecciones { get; set; }
    }
}
