//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubEtapas
    {
        public tbl_SubEtapas()
        {
            this.Config_FechasSubEtapasProyecto = new HashSet<Config_FechasSubEtapasProyecto>();
            this.Config_SubEtapaIndicador = new HashSet<Config_SubEtapaIndicador>();
            this.Dashboard_PublicacionProyectoSubetapa = new HashSet<Dashboard_PublicacionProyectoSubetapa>();
        }
    
        public int IdSubEtapa { get; set; }
        public Nullable<int> IdEtapa { get; set; }
        public string NombreSubEtapa { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<double> Clave { get; set; }
    
        public virtual ICollection<Config_FechasSubEtapasProyecto> Config_FechasSubEtapasProyecto { get; set; }
        public virtual ICollection<Config_SubEtapaIndicador> Config_SubEtapaIndicador { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectoSubetapa> Dashboard_PublicacionProyectoSubetapa { get; set; }
        public virtual tbl_Responsables tbl_Responsables { get; set; }
        public virtual tbl_Responsables tbl_Responsables1 { get; set; }
        public virtual tbl_Responsables tbl_Responsables2 { get; set; }
    }
}
