//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Elementos
    {
        public tbl_Elementos()
        {
            this.Dashboard_PublicacionElemento = new HashSet<Dashboard_PublicacionElemento>();
        }
    
        public int IdElemento { get; set; }
        public Nullable<int> IdSubsistema { get; set; }
        public string NombreElemento { get; set; }
        public string DescripcionElemento { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
    
        public virtual ICollection<Dashboard_PublicacionElemento> Dashboard_PublicacionElemento { get; set; }
        public virtual tbl_Subsistemas tbl_Subsistemas { get; set; }
    }
}
