//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Revisiones
    {
        public int idRevisiones { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<int> IdConfigIndicadorResponsable { get; set; }
    
        public virtual Config_IndicadorResponsable Config_IndicadorResponsable { get; set; }
    }
}
