//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SoportesAsignadosaIndicador
    {
        public int IdSoportesAsignadosaIndicador { get; set; }
        public string RutaDoc { get; set; }
        public string NombreDoc { get; set; }
        public Nullable<int> IdDataValoresIndicadores { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Data_ValoresIndicador Data_ValoresIndicador { get; set; }
    }
}
