//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Etapas
    {
        public tbl_Etapas()
        {
            this.Config_FechasEtapasProyecto = new HashSet<Config_FechasEtapasProyecto>();
            this.Dashboard_PublicacionProyectoEtapa = new HashSet<Dashboard_PublicacionProyectoEtapa>();
            this.Dashboard_PublicacionProyectoSubetapa = new HashSet<Dashboard_PublicacionProyectoSubetapa>();
        }
    
        public int IdEtapa { get; set; }
        public string NombreEtapa { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<int> Clave { get; set; }
    
        public virtual ICollection<Config_FechasEtapasProyecto> Config_FechasEtapasProyecto { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectoEtapa> Dashboard_PublicacionProyectoEtapa { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectoSubetapa> Dashboard_PublicacionProyectoSubetapa { get; set; }
        public virtual tbl_Responsables tbl_Responsables { get; set; }
    }
}
