//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subsistemas
    {
        public tbl_Subsistemas()
        {
            this.Dashboard_PublicacionAvanceSubsistema = new HashSet<Dashboard_PublicacionAvanceSubsistema>();
            this.Dashboard_PublicacionElemento = new HashSet<Dashboard_PublicacionElemento>();
            this.Dashboard_PublicacionTabular = new HashSet<Dashboard_PublicacionTabular>();
            this.RunTime_PorcentajesProyecto = new HashSet<RunTime_PorcentajesProyecto>();
            this.tbl_Elementos = new HashSet<tbl_Elementos>();
        }
    
        public int IdSubsistema { get; set; }
        public string NombreSubsistema { get; set; }
        public string DescripcionLargaSubsistema { get; set; }
        public Nullable<bool> CheckAplicaProyecto { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Semaforo { get; set; }
        public Nullable<int> Porcentaje { get; set; }
    
        public virtual ICollection<Dashboard_PublicacionAvanceSubsistema> Dashboard_PublicacionAvanceSubsistema { get; set; }
        public virtual ICollection<Dashboard_PublicacionElemento> Dashboard_PublicacionElemento { get; set; }
        public virtual ICollection<Dashboard_PublicacionTabular> Dashboard_PublicacionTabular { get; set; }
        public virtual ICollection<RunTime_PorcentajesProyecto> RunTime_PorcentajesProyecto { get; set; }
        public virtual ICollection<tbl_Elementos> tbl_Elementos { get; set; }
    }
}
