//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subdirecciones
    {
        public tbl_Subdirecciones()
        {
            this.tbl_Gerencias = new HashSet<tbl_Gerencias>();
        }
    
        public int IdSubdireccion { get; set; }
        public string NombreSubdireccion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string ClaveSubdireccion { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<tbl_Gerencias> tbl_Gerencias { get; set; }
    }
}
