//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ubicaciones
    {
        public tbl_Ubicaciones()
        {
            this.tbl_Proyectos = new HashSet<tbl_Proyectos>();
            this.tbl_Responsables = new HashSet<tbl_Responsables>();
        }
    
        public int idUbicacion { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual ICollection<tbl_Proyectos> tbl_Proyectos { get; set; }
        public virtual ICollection<tbl_Responsables> tbl_Responsables { get; set; }
    }
}
