//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Coordinaciones
    {
        public tbl_Coordinaciones()
        {
            this.tbl_Superintendencias = new HashSet<tbl_Superintendencias>();
        }
    
        public int IdCoordinacion { get; set; }
        public string NombreCoordinacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<int> IdGerencia { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string ClaveCoordinaciones { get; set; }
        public string Tipo { get; set; }
    
        public virtual tbl_Gerencias tbl_Gerencias { get; set; }
        public virtual ICollection<tbl_Superintendencias> tbl_Superintendencias { get; set; }
    }
}
