//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RendicionCuentasServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Responsables
    {
        public tbl_Responsables()
        {
            this.Config_IndicadorResponsable = new HashSet<Config_IndicadorResponsable>();
            this.Dashboard_PublicacionProyectos = new HashSet<Dashboard_PublicacionProyectos>();
            this.Rel_ProgramaAsociadoIndicador = new HashSet<Rel_ProgramaAsociadoIndicador>();
            this.Rel_ProgramaAsociadoIndicador1 = new HashSet<Rel_ProgramaAsociadoIndicador>();
            this.tbl_Etapas = new HashSet<tbl_Etapas>();
            this.tbl_Organigrama = new HashSet<tbl_Organigrama>();
            this.tbl_Organigrama1 = new HashSet<tbl_Organigrama>();
            this.tbl_Proyectos = new HashSet<tbl_Proyectos>();
            this.tbl_Proyectos1 = new HashSet<tbl_Proyectos>();
            this.tbl_Proyectos2 = new HashSet<tbl_Proyectos>();
            this.tbl_SubEtapas = new HashSet<tbl_SubEtapas>();
            this.tbl_SubEtapas1 = new HashSet<tbl_SubEtapas>();
            this.tbl_SubEtapas2 = new HashSet<tbl_SubEtapas>();
        }
    
        public int idResponsable { get; set; }
        public string NombreResponsable { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public string Correo { get; set; }
        public string Ficha { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdAquienReporta { get; set; }
        public string Rol { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
    
        public virtual ICollection<Config_IndicadorResponsable> Config_IndicadorResponsable { get; set; }
        public virtual ICollection<Dashboard_PublicacionProyectos> Dashboard_PublicacionProyectos { get; set; }
        public virtual ICollection<Rel_ProgramaAsociadoIndicador> Rel_ProgramaAsociadoIndicador { get; set; }
        public virtual ICollection<Rel_ProgramaAsociadoIndicador> Rel_ProgramaAsociadoIndicador1 { get; set; }
        public virtual ICollection<tbl_Etapas> tbl_Etapas { get; set; }
        public virtual ICollection<tbl_Organigrama> tbl_Organigrama { get; set; }
        public virtual ICollection<tbl_Organigrama> tbl_Organigrama1 { get; set; }
        public virtual ICollection<tbl_Proyectos> tbl_Proyectos { get; set; }
        public virtual ICollection<tbl_Proyectos> tbl_Proyectos1 { get; set; }
        public virtual ICollection<tbl_Proyectos> tbl_Proyectos2 { get; set; }
        public virtual tbl_Ubicaciones tbl_Ubicaciones { get; set; }
        public virtual ICollection<tbl_SubEtapas> tbl_SubEtapas { get; set; }
        public virtual ICollection<tbl_SubEtapas> tbl_SubEtapas1 { get; set; }
        public virtual ICollection<tbl_SubEtapas> tbl_SubEtapas2 { get; set; }
    }
}
