CREATE TABLE [dbo].[Rel_ProgramaAsociadoIndicador] (
    [IdRelProgramaAsociado]        INT           IDENTITY (1, 1) NOT NULL,
    [IdIndicador]                  INT           NULL,
    [EneroProg]                    INT           NULL,
    [FebreroProg]                  INT           NULL,
    [MarzoProg]                    INT           NULL,
    [AbrilProg]                    INT           NULL,
    [MayoProg]                     INT           NULL,
    [JunioProg]                    INT           NULL,
    [JulioProg]                    INT           NULL,
    [AgostoProg]                   INT           NULL,
    [SeptiembreProg]               INT           NULL,
    [OctubreProg]                  INT           NULL,
    [NoviembreProg]                INT           NULL,
    [DiciembreProg]                INT           NULL,
    [ProyeccionAnualProg]          INT           NULL,
    [AnioSiguienteProg]            INT           NULL,
    [AnioAnteriorReal]             INT           NULL,
    [EneroReal]                    INT           NULL,
    [FebreroReal]                  INT           NULL,
    [MarzoReal]                    INT           NULL,
    [AbrilReal]                    INT           NULL,
    [MayoReal]                     INT           NULL,
    [JunioReal]                    INT           NULL,
    [JulioReal]                    INT           NULL,
    [AgostoReal]                   INT           NULL,
    [SeptiembreReal]               INT           NULL,
    [OctubreReal]                  INT           NULL,
    [NoviembreReal]                INT           NULL,
    [DiciembreReal]                INT           NULL,
    [ProyeccionAnualReal]          INT           NULL,
    [AnioSiguienteReal]            INT           NULL,
    [FecCreacion]                  DATETIME      NULL,
    [IdConfigIndicadorResponsable] INT           NULL,
    [Tipo]                         NVARCHAR (50) NULL,
    [AnioAnteriorProg]             INT           NULL,
    [FechaCreacion]                DATE          NULL,
    [UsuarioCreacion]              INT           NULL,
    [FechaActualizacion]           DATE          NULL,
    [UsuarioActualizacion]         INT           NULL,
    CONSTRAINT [PK_Rel_ProgramaAsociadoIndicador] PRIMARY KEY CLUSTERED ([IdRelProgramaAsociado] ASC),
    CONSTRAINT [FK_Rel_ProgramaAsociadoIndicador_Config_IndicadorResponsable] FOREIGN KEY ([IdConfigIndicadorResponsable]) REFERENCES [dbo].[Config_IndicadorResponsable] ([IdConfigIndicadorResponsable]),
    CONSTRAINT [FK_Rel_ProgramaAsociadoIndicador_tbl_Indicadores] FOREIGN KEY ([IdIndicador]) REFERENCES [dbo].[tbl_Indicadores] ([IdIndicador]) ON DELETE CASCADE,
    CONSTRAINT [FK_Rel_ProgramaAsociadoIndicador_tbl_Responsables] FOREIGN KEY ([UsuarioCreacion]) REFERENCES [dbo].[tbl_Responsables] ([idResponsable]),
    CONSTRAINT [FK_Rel_ProgramaAsociadoIndicador_tbl_Responsables1] FOREIGN KEY ([UsuarioActualizacion]) REFERENCES [dbo].[tbl_Responsables] ([idResponsable])
);





