CREATE TABLE [dbo].[tbl_Historico] (
    [IdHistoricDataProys]          INT            IDENTITY (1, 1) NOT NULL,
    [IdConfigIndicadorResponsable] INT            NULL,
    [Prefijo]                      NVARCHAR (300) NULL,
    [DescripcionCorta]             NVARCHAR (MAX) NULL,
    [EstatusLlenado]               NVARCHAR (100) NULL,
    [TipoIndicador]                NVARCHAR (100) NULL,
    [TipoFrecuencia]               INT            NULL,
    [TipoCalculo]                  NVARCHAR (50)  NULL,
    [Meta]                         INT            NULL,
    [IdProyecto]                   INT            NULL,
    [IdEtapa]                      INT            NULL,
    [IdSubEtapa]                   INT            NULL,
    [IdDataValoresIndicadores]     INT            NULL,
    [Valor]                        INT            NULL,
    [CheckReqSoporte]              BIT            NULL,
    [CheckReqComentario]           BIT            NULL,
    [CheckSoporte]                 BIT            NULL,
    [CheckComentarios]             BIT            NULL,
    [IdElemento]                   INT            NULL,
    [IdIndicador]                  INT            NULL,
    [IdSubsistema]                 INT            NULL,
    [ClaveEtapa]                   INT            NULL,
    [NombreEtapa]                  NVARCHAR (500) NULL,
    [ClaveSubEtapa]                FLOAT (53)     NULL,
    [NombreSubEtapa]               NVARCHAR (500) NULL,
    [NombreSubsistema]             NVARCHAR (50)  NULL,
    [DescripcionLargaSubsistema]   NVARCHAR (500) NULL,
    [NombreElemento]               NVARCHAR (300) NULL,
    [DescripcionElemento]          NVARCHAR (500) NULL,
    [FechaFinEtapa]                DATE           NULL,
    [FechaFinSubEtapa]             DATE           NULL,
    [SemaforoSoportes]             NVARCHAR (100) NULL,
    [SemaforoComentarios]          NVARCHAR (100) NULL,
    [Semaforo]                     NVARCHAR (100) NULL,
    [IdResponsable]                INT            NULL,
    [EstatusSubEtapa]              BIT            NULL,
    [FechaInicioEtapa]             DATE           NULL,
    [FechaInicioSubEtapa]          DATE           NULL,
    [DayGenerated]                 DATE           NULL,
    [NombreResponsable]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_tbl_Historico] PRIMARY KEY CLUSTERED ([IdHistoricDataProys] ASC)
);

